static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Instrumentation/CCD/ImgGrabber/Device/src/ClassFactory.cpp,v 1.4 2010-09-15 16:57:03 vince_soleil Exp $";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: vince_soleil $
//
// $Revision: 1.4 $
//
// $Log: not supported by cvs2svn $
// Revision 1.1.2.3  2010/04/20 11:28:43  vince_soleil
// replaced by version from HEAD
//
// Revision 1.3  2009/04/20 11:53:06  julien_malik
// add IMGGRABBER_INCLUDES_IMGANALYZER macro to disable ImgBeamAnalyzer integration in ImgGrabber if desired
//
// Revision 1.2  2009/03/26 15:28:53  julien_malik
// include Ramon Sune evolutions :
// - direct memory-link with ImgBeamAnalyzer
// - PylonV2 Basler plugin
// - synchronization fixes
// - ImageCounter attribute
// - linux compilation
//
// Revision 1.1  2007/08/20 15:03:20  stephle
// initial import
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================


#include <ImgGrabberClass.h>

#ifdef IMGGRABBER_INCLUDES_IMGANALYZER
#  include <ImgBeamAnalyzerClass.h>
#  include "IBASourceBypass.h"
#endif

/**
 *	Create ImgGrabberClass singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{
#ifdef IMGGRABBER_INCLUDES_IMGANALYZER
  IBASourceFactoryBypass::register_factory();
#endif

  add_class(ImgGrabber_ns::ImgGrabberClass::init("ImgGrabber"));

#ifdef IMGGRABBER_INCLUDES_IMGANALYZER
  add_class(ImgBeamAnalyzer_ns::ImgBeamAnalyzerClass::init("ImgBeamAnalyzer"));
#endif
}
