static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Instrumentation/CCD/ImgGrabber/Device/src/ImgGrabberStateMachine.cpp,v 1.2 2010-09-14 14:49:20 vince_soleil Exp $";
//+=============================================================================
//
// file :         ImgGrabberStateMachine.cpp
//
// description :  C++ source for the ImgGrabber and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author: vince_soleil $
//
// $Revision: 1.2 $
//
// $Log: not supported by cvs2svn $
// Revision 1.1.2.3  2010/04/20 11:28:43  vince_soleil
// replaced by version from HEAD
//
// Revision 1.3  2008/03/05 13:31:57  julien_malik
// - add 'SaveSettings' command
// - support external trigger for Basler cameras
//
// Revision 1.2  2007/10/23 16:29:28  julien_malik
// rework the movie saving
//
// Revision 1.1  2007/08/20 15:03:22  stephle
// initial import
//
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <ImgGrabber.h>
#include <ImgGrabberClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace ImgGrabber_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_Image_allowed
// 
// description : 	Read/Write allowed for Image attribute.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_Image_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_CurrentlySavingMovie_allowed
// 
// description : 	Read/Write allowed for CurrentlySavingMovie attribute.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_CurrentlySavingMovie_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_MovieRemainingTime_allowed
// 
// description : 	Read/Write allowed for MovieRemainingTime attribute.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_MovieRemainingTime_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_Open_allowed
// 
// description : 	Execution allowed for Open command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_Open_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_Close_allowed
// 
// description : 	Execution allowed for Close command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_Close_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_Start_allowed
// 
// description : 	Execution allowed for Start command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_Start_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_Stop_allowed
// 
// description : 	Execution allowed for Stop command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_Stop_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_StartSaveMovie_allowed
// 
// description : 	Execution allowed for StartSaveMovie command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_StartSaveMovie_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_StopSaveMovie_allowed
// 
// description : 	Execution allowed for StopSaveMovie command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_StopSaveMovie_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_Snap_allowed
// 
// description : 	Execution allowed for Snap command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_Snap_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_SetROI_allowed
// 
// description : 	Execution allowed for SetROI command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_SetROI_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_GetROI_allowed
// 
// description : 	Execution allowed for GetROI command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_GetROI_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_ResetROI_allowed
// 
// description : 	Execution allowed for ResetROI command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_ResetROI_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_GetPluginInfo_allowed
// 
// description : 	Execution allowed for GetPluginInfo command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_GetPluginInfo_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		ImgGrabber::is_SaveSettings_allowed
// 
// description : 	Execution allowed for SaveSettings command.
//
//-----------------------------------------------------------------------------
bool ImgGrabber::is_SaveSettings_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace ImgGrabber_ns
